export interface Country {
  code: string;       // ISO 2-letter code
  name: string;       // ชื่อประเทศ
  phoneCode: string;  // รหัสโทรศัพท์
  flag: string;       // Emoji (ถ้าไม่ได้ใช้รูป)
  nationality: string; // สัญชาติ
}

export const countries: Country[] = [
  { code: 'AF', name: 'Afghanistan', phoneCode: '+93', flag: '🇦🇫', nationality: 'Afghan' },
  { code: 'AL', name: 'Albania', phoneCode: '+355', flag: '🇦🇱', nationality: 'Albanian' },
  { code: 'DZ', name: 'Algeria', phoneCode: '+213', flag: '🇩🇿', nationality: 'Algerian' },
  { code: 'AD', name: 'Andorra', phoneCode: '+376', flag: '🇦🇩', nationality: 'Andorran' },
  { code: 'AO', name: 'Angola', phoneCode: '+244', flag: '🇦🇴', nationality: 'Angolan' },
  { code: 'AG', name: 'Antigua and Barbuda', phoneCode: '+1-268', flag: '🇦🇬', nationality: 'Antiguan / Barbudan' },
  { code: 'AR', name: 'Argentina', phoneCode: '+54', flag: '🇦🇷', nationality: 'Argentine' },
  { code: 'AM', name: 'Armenia', phoneCode: '+374', flag: '🇦🇲', nationality: 'Armenian' },
  { code: 'AU', name: 'Australia', phoneCode: '+61', flag: '🇦🇺', nationality: 'Australian' },
  { code: 'AT', name: 'Austria', phoneCode: '+43', flag: '🇦🇹', nationality: 'Austrian' },
  { code: 'AZ', name: 'Azerbaijan', phoneCode: '+994', flag: '🇦🇿', nationality: 'Azerbaijani' },
  { code: 'BS', name: 'Bahamas', phoneCode: '+1-242', flag: '🇧🇸', nationality: 'Bahamian' },
  { code: 'BH', name: 'Bahrain', phoneCode: '+973', flag: '🇧🇭', nationality: 'Bahraini' },
  { code: 'BD', name: 'Bangladesh', phoneCode: '+880', flag: '🇧🇩', nationality: 'Bangladeshi' },
  { code: 'BB', name: 'Barbados', phoneCode: '+1-246', flag: '🇧🇧', nationality: 'Barbadian' },
  { code: 'BY', name: 'Belarus', phoneCode: '+375', flag: '🇧🇾', nationality: 'Belarusian' },
  { code: 'BE', name: 'Belgium', phoneCode: '+32', flag: '🇧🇪', nationality: 'Belgian' },
  { code: 'BZ', name: 'Belize', phoneCode: '+501', flag: '🇧🇿', nationality: 'Belizean' },
  { code: 'BJ', name: 'Benin', phoneCode: '+229', flag: '🇧🇯', nationality: 'Beninese' },
  { code: 'BT', name: 'Bhutan', phoneCode: '+975', flag: '🇧🇹', nationality: 'Bhutanese' },
  { code: 'BO', name: 'Bolivia', phoneCode: '+591', flag: '🇧🇴', nationality: 'Bolivian' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phoneCode: '+387', flag: '🇧🇦', nationality: 'Bosnian / Herzegovinian' },
  { code: 'BW', name: 'Botswana', phoneCode: '+267', flag: '🇧🇼', nationality: 'Motswana' },
  { code: 'BR', name: 'Brazil', phoneCode: '+55', flag: '🇧🇷', nationality: 'Brazilian' },
  { code: 'BN', name: 'Brunei', phoneCode: '+673', flag: '🇧🇳', nationality: 'Bruneian' },
  { code: 'BG', name: 'Bulgaria', phoneCode: '+359', flag: '🇧🇬', nationality: 'Bulgarian' },
  { code: 'BF', name: 'Burkina Faso', phoneCode: '+226', flag: '🇧🇫', nationality: 'Burkinabé' },
  { code: 'BI', name: 'Burundi', phoneCode: '+257', flag: '🇧🇮', nationality: 'Burundian' },
  { code: 'CV', name: 'Cabo Verde', phoneCode: '+238', flag: '🇨🇻', nationality: 'Cape Verdean' },
  { code: 'KH', name: 'Cambodia', phoneCode: '+855', flag: '🇰🇭', nationality: 'Cambodian' },
  { code: 'CM', name: 'Cameroon', phoneCode: '+237', flag: '🇨🇲', nationality: 'Cameroonian' },
  { code: 'CA', name: 'Canada', phoneCode: '+1', flag: '🇨🇦', nationality: 'Canadian' },
  { code: 'CF', name: 'Central African Republic', phoneCode: '+236', flag: '🇨🇫', nationality: 'Central African' },
  { code: 'TD', name: 'Chad', phoneCode: '+235', flag: '🇹🇩', nationality: 'Chadian' },
  { code: 'CL', name: 'Chile', phoneCode: '+56', flag: '🇨🇱', nationality: 'Chilean' },
  { code: 'CN', name: 'China', phoneCode: '+86', flag: '🇨🇳', nationality: 'Chinese' },
  { code: 'CO', name: 'Colombia', phoneCode: '+57', flag: '🇨🇴', nationality: 'Colombian' },
  { code: 'KM', name: 'Comoros', phoneCode: '+269', flag: '🇰🇲', nationality: 'Comorian' },
  { code: 'CG', name: 'Congo', phoneCode: '+242', flag: '🇨🇬', nationality: 'Congolese' },
  { code: 'CD', name: 'Congo (DRC)', phoneCode: '+243', flag: '🇨🇩', nationality: 'Congolese' },
  { code: 'CR', name: 'Costa Rica', phoneCode: '+506', flag: '🇨🇷', nationality: 'Costa Rican' },
  { code: 'CI', name: "Côte d'Ivoire", phoneCode: '+225', flag: '🇨🇮', nationality: 'Ivorian' },
  { code: 'HR', name: 'Croatia', phoneCode: '+385', flag: '🇭🇷', nationality: 'Croatian' },
  { code: 'CU', name: 'Cuba', phoneCode: '+53', flag: '🇨🇺', nationality: 'Cuban' },
  { code: 'CY', name: 'Cyprus', phoneCode: '+357', flag: '🇨🇾', nationality: 'Cypriot' },
  { code: 'CZ', name: 'Czech Republic', phoneCode: '+420', flag: '🇨🇿', nationality: 'Czech' },
  { code: 'DK', name: 'Denmark', phoneCode: '+45', flag: '🇩🇰', nationality: 'Danish' },
  { code: 'DJ', name: 'Djibouti', phoneCode: '+253', flag: '🇩🇯', nationality: 'Djiboutian' },
  { code: 'DM', name: 'Dominica', phoneCode: '+1-767', flag: '🇩🇲', nationality: 'Dominican' },
  { code: 'DO', name: 'Dominican Republic', phoneCode: '+1-809', flag: '🇩🇴', nationality: 'Dominican' },
  { code: 'EC', name: 'Ecuador', phoneCode: '+593', flag: '🇪🇨', nationality: 'Ecuadorian' },
  { code: 'EG', name: 'Egypt', phoneCode: '+20', flag: '🇪🇬', nationality: 'Egyptian' },
  { code: 'SV', name: 'El Salvador', phoneCode: '+503', flag: '🇸🇻', nationality: 'Salvadoran' },
  { code: 'GQ', name: 'Equatorial Guinea', phoneCode: '+240', flag: '🇬🇶', nationality: 'Equatoguinean' },
  { code: 'ER', name: 'Eritrea', phoneCode: '+291', flag: '🇪🇷', nationality: 'Eritrean' },
  { code: 'EE', name: 'Estonia', phoneCode: '+372', flag: '🇪🇪', nationality: 'Estonian' },
  { code: 'SZ', name: 'Eswatini', phoneCode: '+268', flag: '🇸🇿', nationality: 'Swazi' },
  { code: 'ET', name: 'Ethiopia', phoneCode: '+251', flag: '🇪🇹', nationality: 'Ethiopian' },
  { code: 'FJ', name: 'Fiji', phoneCode: '+679', flag: '🇫🇯', nationality: 'Fijian' },
  { code: 'FI', name: 'Finland', phoneCode: '+358', flag: '🇫🇮', nationality: 'Finnish' },
  { code: 'FR', name: 'France', phoneCode: '+33', flag: '🇫🇷', nationality: 'French' },
  { code: 'GA', name: 'Gabon', phoneCode: '+241', flag: '🇬🇦', nationality: 'Gabonese' },
  { code: 'GM', name: 'Gambia', phoneCode: '+220', flag: '🇬🇲', nationality: 'Gambian' },
  { code: 'GE', name: 'Georgia', phoneCode: '+995', flag: '🇬🇪', nationality: 'Georgian' },
  { code: 'DE', name: 'Germany', phoneCode: '+49', flag: '🇩🇪', nationality: 'German' },
  { code: 'GH', name: 'Ghana', phoneCode: '+233', flag: '🇬🇭', nationality: 'Ghanaian' },
  { code: 'GR', name: 'Greece', phoneCode: '+30', flag: '🇬🇷', nationality: 'Greek' },
  { code: 'GD', name: 'Grenada', phoneCode: '+1-473', flag: '🇬🇩', nationality: 'Grenadian' },
  { code: 'GT', name: 'Guatemala', phoneCode: '+502', flag: '🇬🇹', nationality: 'Guatemalan' },
  { code: 'GN', name: 'Guinea', phoneCode: '+224', flag: '🇬🇳', nationality: 'Guinean' },
  { code: 'GW', name: 'Guinea-Bissau', phoneCode: '+245', flag: '🇬🇼', nationality: 'Bissau-Guinean' },
  { code: 'GY', name: 'Guyana', phoneCode: '+592', flag: '🇬🇾', nationality: 'Guyanese' },
  { code: 'HT', name: 'Haiti', phoneCode: '+509', flag: '🇭🇹', nationality: 'Haitian' },
  { code: 'HN', name: 'Honduras', phoneCode: '+504', flag: '🇭🇳', nationality: 'Honduran' },
  { code: 'HK', name: 'Hong Kong', phoneCode: '+852', flag: '🇭🇰', nationality: 'Hong Konger' },
  { code: 'HU', name: 'Hungary', phoneCode: '+36', flag: '🇭🇺', nationality: 'Hungarian' },
  { code: 'IS', name: 'Iceland', phoneCode: '+354', flag: '🇮🇸', nationality: 'Icelandic' },
  { code: 'IN', name: 'India', phoneCode: '+91', flag: '🇮🇳', nationality: 'Indian' },
  { code: 'ID', name: 'Indonesia', phoneCode: '+62', flag: '🇮🇩', nationality: 'Indonesian' },
  { code: 'IR', name: 'Iran', phoneCode: '+98', flag: '🇮🇷', nationality: 'Iranian' },
  { code: 'IQ', name: 'Iraq', phoneCode: '+964', flag: '🇮🇶', nationality: 'Iraqi' },
  { code: 'IE', name: 'Ireland', phoneCode: '+353', flag: '🇮🇪', nationality: 'Irish' },
  { code: 'IL', name: 'Israel', phoneCode: '+972', flag: '🇮🇱', nationality: 'Israeli' },
  { code: 'IT', name: 'Italy', phoneCode: '+39', flag: '🇮🇹', nationality: 'Italian' },
  { code: 'JM', name: 'Jamaica', phoneCode: '+1-876', flag: '🇯🇲', nationality: 'Jamaican' },
  { code: 'JP', name: 'Japan', phoneCode: '+81', flag: '🇯🇵', nationality: 'Japanese' },
  { code: 'JO', name: 'Jordan', phoneCode: '+962', flag: '🇯🇴', nationality: 'Jordanian' },
  { code: 'KZ', name: 'Kazakhstan', phoneCode: '+7', flag: '🇰🇿', nationality: 'Kazakhstani' },
  { code: 'KE', name: 'Kenya', phoneCode: '+254', flag: '🇰🇪', nationality: 'Kenyan' },
  { code: 'KI', name: 'Kiribati', phoneCode: '+686', flag: '🇰🇮', nationality: 'I-Kiribati' },
  { code: 'KP', name: 'Korea (North)', phoneCode: '+850', flag: '🇰🇵', nationality: 'North Korean' },
  { code: 'KR', name: 'Korea (South)', phoneCode: '+82', flag: '🇰🇷', nationality: 'South Korean' },
  { code: 'KW', name: 'Kuwait', phoneCode: '+965', flag: '🇰🇼', nationality: 'Kuwaiti' },
  { code: 'KG', name: 'Kyrgyzstan', phoneCode: '+996', flag: '🇰🇬', nationality: 'Kyrgyz' },
  { code: 'LA', name: 'Lao', phoneCode: '+856', flag: '🇱🇦', nationality: 'Lao' },
  { code: 'LV', name: 'Latvia', phoneCode: '+371', flag: '🇱🇻', nationality: 'Latvian' },
  { code: 'LB', name: 'Lebanon', phoneCode: '+961', flag: '🇱🇧', nationality: 'Lebanese' },
  { code: 'LS', name: 'Lesotho', phoneCode: '+266', flag: '🇱🇸', nationality: 'Basotho' },
  { code: 'LR', name: 'Liberia', phoneCode: '+231', flag: '🇱🇷', nationality: 'Liberian' },
  { code: 'LY', name: 'Libya', phoneCode: '+218', flag: '🇱🇾', nationality: 'Libyan' },
  { code: 'LI', name: 'Liechtenstein', phoneCode: '+423', flag: '🇱🇮', nationality: 'Liechtensteiner' },
  { code: 'LT', name: 'Lithuania', phoneCode: '+370', flag: '🇱🇹', nationality: 'Lithuanian' },
  { code: 'LU', name: 'Luxembourg', phoneCode: '+352', flag: '🇱🇺', nationality: 'Luxembourgish' },
  { code: 'MO', name: 'Macau', phoneCode: '+853', flag: '🇲🇴', nationality: 'Macanese' },
  { code: 'MG', name: 'Madagascar', phoneCode: '+261', flag: '🇲🇬', nationality: 'Malagasy' },
  { code: 'MW', name: 'Malawi', phoneCode: '+265', flag: '🇲🇼', nationality: 'Malawian' },
  { code: 'MY', name: 'Malaysia', phoneCode: '+60', flag: '🇲🇾', nationality: 'Malaysian' },
  { code: 'MV', name: 'Maldives', phoneCode: '+960', flag: '🇲🇻', nationality: 'Maldivian' },
  { code: 'ML', name: 'Mali', phoneCode: '+223', flag: '🇲🇱', nationality: 'Malian' },
  { code: 'MT', name: 'Malta', phoneCode: '+356', flag: '🇲🇹', nationality: 'Maltese' },
  { code: 'MH', name: 'Marshall Islands', phoneCode: '+692', flag: '🇲🇭', nationality: 'Marshallese' },
  { code: 'MR', name: 'Mauritania', phoneCode: '+222', flag: '🇲🇷', nationality: 'Mauritanian' },
  { code: 'MU', name: 'Mauritius', phoneCode: '+230', flag: '🇲🇺', nationality: 'Mauritian' },
  { code: 'MX', name: 'Mexico', phoneCode: '+52', flag: '🇲🇽', nationality: 'Mexican' },
  { code: 'FM', name: 'Micronesia', phoneCode: '+691', flag: '🇫🇲', nationality: 'Micronesian' },
  { code: 'MD', name: 'Moldova', phoneCode: '+373', flag: '🇲🇩', nationality: 'Moldovan' },
  { code: 'MC', name: 'Monaco', phoneCode: '+377', flag: '🇲🇨', nationality: 'Monégasque' },
  { code: 'MN', name: 'Mongolia', phoneCode: '+976', flag: '🇲🇳', nationality: 'Mongolian' },
  { code: 'ME', name: 'Montenegro', phoneCode: '+382', flag: '🇲🇪', nationality: 'Montenegrin' },
  { code: 'MA', name: 'Morocco', phoneCode: '+212', flag: '🇲🇦', nationality: 'Moroccan' },
  { code: 'MZ', name: 'Mozambique', phoneCode: '+258', flag: '🇲🇿', nationality: 'Mozambican' },
  { code: 'MM', name: 'Myanmar', phoneCode: '+95', flag: '🇲🇲', nationality: 'Burmese' },
  { code: 'NA', name: 'Namibia', phoneCode: '+264', flag: '🇳🇦', nationality: 'Namibian' },
  { code: 'NR', name: 'Nauru', phoneCode: '+674', flag: '🇳🇷', nationality: 'Nauruan' },
  { code: 'NP', name: 'Nepal', phoneCode: '+977', flag: '🇳🇵', nationality: 'Nepali' },
  { code: 'NL', name: 'Netherlands', phoneCode: '+31', flag: '🇳🇱', nationality: 'Dutch' },
  { code: 'NZ', name: 'New Zealand', phoneCode: '+64', flag: '🇳🇿', nationality: 'New Zealander' },
  { code: 'NI', name: 'Nicaragua', phoneCode: '+505', flag: '🇳🇮', nationality: 'Nicaraguan' },
  { code: 'NE', name: 'Niger', phoneCode: '+227', flag: '🇳🇪', nationality: 'Nigerien' },
  { code: 'NG', name: 'Nigeria', phoneCode: '+234', flag: '🇳🇬', nationality: 'Nigerian' },
  { code: 'MK', name: 'North Macedonia', phoneCode: '+389', flag: '🇲🇰', nationality: 'Macedonian' },
  { code: 'NO', name: 'Norway', phoneCode: '+47', flag: '🇳🇴', nationality: 'Norwegian' },
  { code: 'OM', name: 'Oman', phoneCode: '+968', flag: '🇴🇲', nationality: 'Omani' },
  { code: 'PK', name: 'Pakistan', phoneCode: '+92', flag: '🇵🇰', nationality: 'Pakistani' },
  { code: 'PW', name: 'Palau', phoneCode: '+680', flag: '🇵🇼', nationality: 'Palauan' },
  { code: 'PS', name: 'Palestine', phoneCode: '+970', flag: '🇵🇸', nationality: 'Palestinian' },
  { code: 'PA', name: 'Panama', phoneCode: '+507', flag: '🇵🇦', nationality: 'Panamanian' },
  { code: 'PG', name: 'Papua New Guinea', phoneCode: '+675', flag: '🇵🇬', nationality: 'Papua New Guinean' },
  { code: 'PY', name: 'Paraguay', phoneCode: '+595', flag: '🇵🇾', nationality: 'Paraguayan' },
  { code: 'PE', name: 'Peru', phoneCode: '+51', flag: '🇵🇪', nationality: 'Peruvian' },
  { code: 'PH', name: 'Philippines', phoneCode: '+63', flag: '🇵🇭', nationality: 'Filipino' },
  { code: 'PL', name: 'Poland', phoneCode: '+48', flag: '🇵🇱', nationality: 'Polish' },
  { code: 'PT', name: 'Portugal', phoneCode: '+351', flag: '🇵🇹', nationality: 'Portuguese' },
  { code: 'QA', name: 'Qatar', phoneCode: '+974', flag: '🇶🇦', nationality: 'Qatari' },
  { code: 'RO', name: 'Romania', phoneCode: '+40', flag: '🇷🇴', nationality: 'Romanian' },
  { code: 'RU', name: 'Russia', phoneCode: '+7', flag: '🇷🇺', nationality: 'Russian' },
  { code: 'RW', name: 'Rwanda', phoneCode: '+250', flag: '🇷🇼', nationality: 'Rwandan' },
  { code: 'KN', name: 'Saint Kitts and Nevis', phoneCode: '+1-869', flag: '🇰🇳', nationality: 'Kittitian / Nevisian' },
  { code: 'LC', name: 'Saint Lucia', phoneCode: '+1-758', flag: '🇱🇨', nationality: 'Saint Lucian' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', phoneCode: '+1-784', flag: '🇻🇨', nationality: 'Vincentian' },
  { code: 'WS', name: 'Samoa', phoneCode: '+685', flag: '🇼🇸', nationality: 'Samoan' },
  { code: 'SM', name: 'San Marino', phoneCode: '+378', flag: '🇸🇲', nationality: 'Sammarinese' },
  { code: 'ST', name: 'São Tomé and Príncipe', phoneCode: '+239', flag: '🇸🇹', nationality: 'São Toméan' },
  { code: 'SA', name: 'Saudi Arabia', phoneCode: '+966', flag: '🇸🇦', nationality: 'Saudi' },
  { code: 'SN', name: 'Senegal', phoneCode: '+221', flag: '🇸🇳', nationality: 'Senegalese' },
  { code: 'RS', name: 'Serbia', phoneCode: '+381', flag: '🇷🇸', nationality: 'Serbian' },
  { code: 'SC', name: 'Seychelles', phoneCode: '+248', flag: '🇸🇨', nationality: 'Seychellois' },
  { code: 'SL', name: 'Sierra Leone', phoneCode: '+232', flag: '🇸🇱', nationality: 'Sierra Leonean' },
  { code: 'SG', name: 'Singapore', phoneCode: '+65', flag: '🇸🇬', nationality: 'Singaporean' },
  { code: 'SK', name: 'Slovakia', phoneCode: '+421', flag: '🇸🇰', nationality: 'Slovak' },
  { code: 'SI', name: 'Slovenia', phoneCode: '+386', flag: '🇸🇮', nationality: 'Slovenian' },
  { code: 'SB', name: 'Solomon Islands', phoneCode: '+677', flag: '🇸🇧', nationality: 'Solomon Islander' },
  { code: 'SO', name: 'Somalia', phoneCode: '+252', flag: '🇸🇴', nationality: 'Somali' },
  { code: 'ZA', name: 'South Africa', phoneCode: '+27', flag: '🇿🇦', nationality: 'South African' },
  { code: 'SS', name: 'South Sudan', phoneCode: '+211', flag: '🇸🇸', nationality: 'South Sudanese' },
  { code: 'ES', name: 'Spain', phoneCode: '+34', flag: '🇪🇸', nationality: 'Spanish' },
  { code: 'LK', name: 'Sri Lanka', phoneCode: '+94', flag: '🇱🇰', nationality: 'Sri Lankan' },
  { code: 'SD', name: 'Sudan', phoneCode: '+249', flag: '🇸🇩', nationality: 'Sudanese' },
  { code: 'SR', name: 'Suriname', phoneCode: '+597', flag: '🇸🇷', nationality: 'Surinamese' },
  { code: 'SE', name: 'Sweden', phoneCode: '+46', flag: '🇸🇪', nationality: 'Swedish' },
  { code: 'CH', name: 'Switzerland', phoneCode: '+41', flag: '🇨🇭', nationality: 'Swiss' },
  { code: 'SY', name: 'Syria', phoneCode: '+963', flag: '🇸🇾', nationality: 'Syrian' },
  { code: 'TW', name: 'Taiwan', phoneCode: '+886', flag: '🇹🇼', nationality: 'Taiwanese' },
  { code: 'TJ', name: 'Tajikistan', phoneCode: '+992', flag: '🇹🇯', nationality: 'Tajik' },
  { code: 'TZ', name: 'Tanzania', phoneCode: '+255', flag: '🇹🇿', nationality: 'Tanzanian' },
  { code: 'TH', name: 'Thailand', phoneCode: '+66', flag: '🇹🇭', nationality: 'Thai' },
  { code: 'TL', name: 'Timor-Leste', phoneCode: '+670', flag: '🇹🇱', nationality: 'Timorese' },
  { code: 'TG', name: 'Togo', phoneCode: '+228', flag: '🇹🇬', nationality: 'Togolese' },
  { code: 'TO', name: 'Tonga', phoneCode: '+676', flag: '🇹🇴', nationality: 'Tongan' },
  { code: 'TT', name: 'Trinidad and Tobago', phoneCode: '+1-868', flag: '🇹🇹', nationality: 'Trinidadian / Tobagonian' },
  { code: 'TN', name: 'Tunisia', phoneCode: '+216', flag: '🇹🇳', nationality: 'Tunisian' },
  { code: 'TR', name: 'Turkey', phoneCode: '+90', flag: '🇹🇷', nationality: 'Turkish' },
  { code: 'TM', name: 'Turkmenistan', phoneCode: '+993', flag: '🇹🇲', nationality: 'Turkmen' },
  { code: 'TV', name: 'Tuvalu', phoneCode: '+688', flag: '🇹🇻', nationality: 'Tuvaluan' },
  { code: 'UG', name: 'Uganda', phoneCode: '+256', flag: '🇺🇬', nationality: 'Ugandan' },
  { code: 'UA', name: 'Ukraine', phoneCode: '+380', flag: '🇺🇦', nationality: 'Ukrainian' },
  { code: 'AE', name: 'United Arab Emirates', phoneCode: '+971', flag: '🇦🇪', nationality: 'Emirati' },
  { code: 'GB', name: 'United Kingdom', phoneCode: '+44', flag: '🇬🇧', nationality: 'British' },
  { code: 'US', name: 'United States', phoneCode: '+1', flag: '🇺🇸', nationality: 'American' },
  { code: 'UY', name: 'Uruguay', phoneCode: '+598', flag: '🇺🇾', nationality: 'Uruguayan' },
  { code: 'UZ', name: 'Uzbekistan', phoneCode: '+998', flag: '🇺🇿', nationality: 'Uzbek' },
  { code: 'VU', name: 'Vanuatu', phoneCode: '+678', flag: '🇻🇺', nationality: 'Ni-Vanuatu' },
  { code: 'VA', name: 'Vatican City', phoneCode: '+379', flag: '🇻🇦', nationality: 'Vatican' },
  { code: 'VE', name: 'Venezuela', phoneCode: '+58', flag: '🇻🇪', nationality: 'Venezuelan' },
  { code: 'VN', name: 'Vietnam', phoneCode: '+84', flag: '🇻🇳', nationality: 'Vietnamese' },
  { code: 'YE', name: 'Yemen', phoneCode: '+967', flag: '🇾🇪', nationality: 'Yemeni' },
  { code: 'ZM', name: 'Zambia', phoneCode: '+260', flag: '🇿🇲', nationality: 'Zambian' },
  { code: 'ZW', name: 'Zimbabwe', phoneCode: '+263', flag: '🇿🇼', nationality: 'Zimbabwean' },];
export const getCountryByCode = (code: string) => countries.find(c => c.code === code);
